//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public decimal Id { get; set; }
        public decimal CatalogId { get; set; }
        public decimal BookId { get; set; }
        public Nullable<decimal> WholesalePrice { get; set; }
        public Nullable<decimal> SoldQuantity { get; set; }
        public Nullable<decimal> StorageQuantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Store Store { get; set; }
    }
}
